### ISSUE TITLE
Fix spelling and grammer

### ISSUE THREAD

**Issue by GarysCorner** [GarysCorner/Covid19-LaCompared#1]
Fix the spelling and grammar in the readme file to give people the false impression you are literate.

**Comment by lakshya-dhariwal** [comment]
Can you assign it to me ? I am new on Github and looking to contribute.

**Comment by chamiduu** [comment]
There are about 15 grammatical errors and spelling mistakes. I can fix them and make a PR real quick if you assign me.

**Comment by GarysCorner** [comment]
Thank you chamindujs for closing this issue with commit https://github.com/GarysCorner/Covid19-LaCompared/commit/cd96342259c097dbe3ea1e222040af57b9afe39b

**Comment by GarysCorner** [comment]
LySergicaciD125, sorry chamindujs had already forked the fix when you requested.  in the future you can just fork the repo, make the correction register pull request which will alert me to merge your changes.  Thanks both of you.
